version: '3'
services:
  elasticsearch:
    image: elasticsearch:7.8.1
    ports:
      - 9200:9200
    environment:
      discovery.type: 'single-node'
      xpack.security.enabled: 'true'
      ELASTIC_PASSWORD: 'changeme'
      ES_JAVA_OPTS: '-Xmx2g -Xms2g'
    networks:
      - default  


  kibana:
    image: kibana:7.8.1
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601

  graghql-server:
    build: ./graghql-server
    container_name: graghql-server
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - ESS_CLOUD_USERNAME=elastic
      - ESS_CLOUD_PASSWORD=changeme
    depends_on:
      - elasticsearch
      - kibana
    ports:
      - "4000:4000" 
    networks:
      - default
    command: npm start 
    

  app:
    build: ./nextjs-app
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - ESS_CLOUD_PASSWORD=changeme
      - ESS_CLOUD_USERNAME=elastic
    depends_on:
      - elasticsearch
      - kibana  
    ports:
      - "3000:3000"
    command: npm start 


networks:
  default:
    driver: bridge